[gammaloop_state]
state_name = "physical_1L_6photons_output"
integration_state_name = "physical_1L_6photons_integration"
process_name = "physical_1L_6photons"

[integrator.madnis]
batch_size = 8192
training_phase = "real"
n_cores = 32
discrete_model = "transformer"
is_vacuum = false

[momtrop]
edge_weight = 0.555555555555

[transformer]
embedding_dim = 128
feedforward_dim = 256
heads = 8
mlp_units = 128
transformer_layers = 2

[layered_integrand]
integrand_type = "gammaloop"
training_phase = "real"
n_cores = 64

[layered_parameterisation.layer_0]
param_type = "kaapo"
mu = 0.0
a = 0.95
b = 1.0

[layered_parameterisation.gagi]
param_type = "MC layer"
mc_weight_type = "e-surface"

[layered_parameterisation.layer_1]
param_type = "inv_spherical"
conformal_scale = 1.0

[layered_parameterisation.layer_2]
param_type = "momtrop"