[graph]
momtrop_edge_weight = 0.83333333333

[gammaloop_state]
state_name = "scalar_3_point_1_loop_output"
integration_state_name = "scalar_3_point_1_loop_integration"
process_name = "scalar_3_point_1_loop"

[integrator.madnis]
batch_size = 2048
discrete_model = "transformer"

[integrator.madnis.transformer]
embedding_dim = 128
feedforward_dim = 256
heads = 2
mlp_units = 128
transformer_layers = 2

[layered_integrand]
integrand_type = "gammaloop"
training_phase = "imag"
n_cores = 2

[plotting_params.training_prog]
n_training_steps = 2000
n_samples = 100000
n_samples_after_training = 1000000
